	</div>
    </div>
    <div id="footerDiv">
        <div id="bottomBarBackgroundDiv"><img class="scaledImg" src="images/bg_main_wide.gif" /></div>
		<div id="aniGif2Div"><img id="aniGif2" src="./images/dmk-rrpm-ani.gif" /></div> 
        <div id="footerText">&#169;2006 DMK Canada - All Rights Reserved.</div>
    </div>
</div>
</center>
<script language="JavaScript" src="./scripts/hilite-nav-item.js"></script>
</body>
</html>

