<div id="topNav">
            <div class="topNavItem"><a href="./">Home</a></div>
            <div class="topNavItem"><a href="./aboutus.php">About Us</a></div>
            <div class="topNavItem"><a href="./concepts.php">Dann&#233; Concept</a></div>
            <div class="topNavItem"><a href="./product-types.php">Products</a></div>
            <!--<div class="topNavItem"><a href="./treatments-home.php">Treatments</a></div>-->
            <div class="topNavItem"><a href="./treatments.php">Treatments</a></div>
            <div class="topNavItem"><a href="./results-gallery.php">Results Gallery</a></div>
            <!--<div class="topNavItem"><a href="./">Case Studies</a></div>
            <div class="topNavItem"><a href="./">FAQ's / Help</a></div>-->
            <!--<div class="topNavItem"><a href="./">Live Studio</a></div>
            <div class="topNavItem"><a href="./">Media Clips</a></div>-->
            <div class="topNavItem"><a href="./articles.php">Articles</a></div>
            <!--<div class="topNavItem"><a href="./">DMK&#174; Education</a></div>-->
            <div class="topNavItem"><a href="./comingevents.php">Coming Events</a></div>
			<div class="topNavItem"><a href="./contactus.php">Contact Us</a></div>
			<div class="eduLinkContainer">
            	<a href="pdtc-form.php"><img src="./images/click_PDT_info.gif" width="140" height="140"/></a>
        	</div>
        </div>
