<?php error_reporting(0); ?>

<html>
<head>
<title>Canadian Domain Name Registration , Low Cost Web Hosting - Siber name.ca</title>
<meta name="description" content="Domain Name Canada, Unix Hosting, Web Marketing, my own email, SSL Certificates - Siber Name.com, Canadian Domain Name Registration , Low Cost Web Site Hosting - Domain Names, Canadian Domains Registrations, email, free email, email address, web position gold reseller, hosting, free web hosting, web hosting, cheap web hosting, web site hosting, domain name, domain, domain registration, domain name registration, domain hosting">
<meta name="keywords" content="inexpensive web hosting, low cost domain name registration,  quality web site hosting services, low price domain name registration, web hosting canada, business web site hosting, cheap web site hosting, cheap domain registration, web domain name registration, cheapest domain name registration, affordable web page hosting, canadian .ca domain name registration,  affordable web hosting services,
web page hosting,free domain registration">
<meta name="robots" content="index,follow">
<meta name="revisit-after" content="10">
<meta name="copyright" content="Copyright 2002 sibername.com All rights reserved">
<meta name="language" content="en">
<meta name="classification" content="Internet Services">
<meta name="distribution" content="Global">
<link rel="stylesheet" href="http://www.sibername.com/cybername.css" type="text/css">
</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor=#416774 text="#daffff" link="#e6dfcc" vlink="#e6dfcc" alink="#e6dfcc">
<table width=774 border=0 cellpadding=0 cellspacing=0>
<tr> 
	<td height=66 colspan=10><a href=http://www.sibername.com><img src="http://sibername.com/images/en/siber-main_02.jpg" width=774  alt="Canadian CA Domain Name Registrations Registrar and Web Site Hosting Services"></a></td>
	<td width=10 height=66><img src="http://www.sibername.com/images/spacer.gif" width=1 height=66></td>
</tr>
</table>

<table width=774 border=0 cellpadding=0 cellspacing=0>
<tr>
	<td valign=top>

	</td>
	<td width=20><img src="http://www.sibername.com/images/spacer.gif" width=20 height=1></td>
	<td valign=top align="left">
	
<p>&nbsp;</p>
<table cellpadding="0" cellspacing="0" border="0" width="75%" align="center">
<tr>
	<td align="center">
	

<b>Under Construction!</b>

<p>


<? if( file_exists( 'sohoadmin' )) { ?>

<div align="center">

<h1>WebSiteMatic Login</h1>

<form name=login method=post action="sohoadmin/index.php">
<table cellpadding="4">
<tr>
 <td align="center">
Username:<br>
<input type="text" name="PHP_AUTH_USER" class=txt style='width: 150px';>
	</td>
</tr>
<tr>
 <td align="center">
Password:<br>
<input type="password" name="PHP_AUTH_PW" class=txt style='width: 150px';>
	</td>
</tr>
<tr>
	<td align="center">
<input type=hidden name=process value=1>
<input type=submit class=txt style='cursor: hand;' value="Login">
	</td>
</tr>
<tr><td>(Please refer to the welcome email for the login details. 
<br>This login is not the same as the sibername account login.)</td></tr>
</table>
</form>
<a href="/sohoadmin/system_requirements.html">System Requirements</a> | 
<a href="/sohoadmin/help.html">Login Help</a>

<p>&nbsp;</p>

Please email us at <a href="mailto: support@sibername.com">support@sibername.com</a> <br>
in case you need help to use this tool



<? } else { ?>


<a href="http://www.sibername.com/user/wsm.php?domain=<?= $_SERVER['HTTP_HOST'] ?>" title="Login to WebSiteMatic CM4ALL">Login to start building your web site</a>
<br>(Please refer to the welcome email for the login details. <br>This login is not the same as the sibername account login.)

<? } ?>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>

You can easily build your web site by using one of the 3 Web Site Building tools we offer. 

Each tools has its pros and cons and you can choose and use any of the tools and also switch 

to another option free of charge.

</p>





<table align="center">

<tr>

<td>



<a href="http://www.sibername.com/canadianwebhosting/demologin.php">WebSiteMatic - SohoLaunch</a><br><br>

<a href="http://www.sibername.com/canadianwebhosting/rvsitebuilder.php">WebSiteMatic - rvSiteBuilder</a><br><br>

<a href="http://www.sibername.com/canadianwebhosting/joomla.php">WebSiteMatic - Joomla</a>



</td></tr>

</table>

</p>


<a href=http://www.sibername.com/en/canadianwebhosting/>This Domain is Hosted by Sibername.com Canadian Web Site Hosting Services</a><br/>
<a href=http://www.sibername.com/en/canadiandomainregistration/>ICANN, CIRA and EURID Accredited Registrar CA Domain Name Registrations</a>
<p>&nbsp;</p>
<p>&nbsp;</p>


	</td>
</tr>
</table>


	</td>
</tr>
<tr>
	<td colspan="2"><img src="http://www.sibername.com/images/spacer.gif" height=300 width=1></td>
	<td class="web-site" align=center>
<p>
&copy;2000 - 2004 Sibername Canadian Business Domain Names Registration and Business Web Site Hosting Canada Inc.<br>
Phone: (800)613-8915 Fax: (613) 482-4626<br>
Address: 275 Slater Street, Suite 900, Ottawa, Ontario, K1P 5H9, CANADA.<br>
All rights reserved. <br>
At Siber Name, you can do it all at one stop, a full service Web Solutions and Web Presence provider. <p>
Ottawa | Montreal | Toronto | Halifax | Vancouver | Victoria | Calgary | Edmonton | Winnipeg | Saskatoon <p> 
	</td>
</tr>
</table>
<img src="http://www.sibername.com/images/spacer.gif" width=1 height=400>
</body>
</html>
