<ul id="certificates">
	<li><strong>2005</strong> - <strong>CSS2</strong> Certificate (Brainbench.com)</li>
	<li><strong>2005</strong> - <strong>XML</strong>  Certificate (Brainbench.com)</li>
	<li><strong>2005</strong> - <strong>PHP4</strong> Certificate (Brainbench.com)</li>
	<li><strong>2005</strong> - <strong>JavaScript</strong> Certificate (Brainbench.com)</li>
	<li><strong>2002</strong> - <strong>SQL and PL/SQL</strong>  Certificate (Oracle)</li>
	<li><strong>2000</strong> - <strong>MS SQL Server 6.5</strong> Certificate (Brainbench.com)</li>
</ul>		