</head>
<body>
<center>
<div id="pageContainerDiv">
    <div id="headerContainer">
        <div id="topBarBackgroundDiv"><img class="scaledImg" src="images/bg_bottom_wide.gif" /></div>
        <div id="dmkLogo"><img src="images/dmk_logo.gif" /></div>
        <div id="anigif1Div"><object
            classid="clsid:D27CDB6E-AE6D-11CF-96B8-444553540000" id="aniGif1"
                        codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0"
                        border="0" width="153" height="100">
                <param name="movie" value="http://dmkatlantic.ca/Header FX.swf" />
                <param name="quality" value="High" />
                <embed src="http://dmkatlantic.ca/Header%20FX.swf" pluginspage="http://www.macromedia.com/go/getflashplayer"
                    type="application/x-shockwave-flash" name="obj1" id="aniGif1" width="153" height="100" quality="High" />
            </object></div>
    </div>
    <div id="contentWrapper">
		<?php include ( "inc/navigation.inc" ); ?>
        <div id="contentArea">

