		<div class="skillSet">
				<div class="subjects"><strong>Operating Systems:</strong></div>
				<div class="skills">Windows XP/2000/NT/ME/98/95, MS DOS, Linux</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">
				<div class="subjects"><strong>Programming Languages:</strong></div>
				<div class="skills">HTML/XHTML/DHTML; CSS1/CSS2; JavaScript/DOM-Scripting/jQuery;<br/>XML/XSL(XPath, XSLT);<br/>PHP 3/4/5, VB Script, JSP;<br/>Java, Visual Basic 6, VB.NET, C, C++, VBA;<br/>SQL, Oracle PL/SQL</div>	
				<div class="clear"></div>
		</div>	
		<div class="skillSet">			
				<div class="subjects"><strong>Technologies:</strong></div>
				<div class="skills">XML, ASP.NET 2.0, JSP, ASP, OOD, RDBMS, ADO, Web 2.0, AJAX</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">			
				<div class="subjects"><strong>Databases:</strong></div>
				<div class="skills">MySQL, Access 2000/2003, Microsoft SQL Server, Oracle 8i/9i</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">			
				<div class="subjects"><strong>Software:</strong></div>
				<div class="skills">MS Office 2003 (MS Word, MS Excel, MS Access, MS Power Point), 
Macromedia Dreamweaver, Macromedia HomeSite, phpMyAdmin, Zend Studio, WinSCP, Adobe Acrobat;  WinCVS, IntelliJ IDEA, CVS, SVN, Star Team</div>
<div class="clear"></div>
		</div>
		<div class="skillSet">			
				<div class="subjects"><strong>Content Management:</strong></div>
				<div class="skills">TOPS (TorStar appropriate Open Publishing System)</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">			
				<div class="subjects"><strong>e-Commerce:</strong></div>
				<div class="skills">Zen Cart</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">
				<div class="subjects"><strong>Internet:</strong></div>
				<div class="skills">Apache, Microsoft IIS, Tomcat, TCP/IP, HTTP, SMTP, FTP</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">		
				<div class="subjects"><strong>Web Design:</strong></div>
				<div class="skills">Wireframes design, developing web site information architecture, layouts, templates, web site usability, accessibility, W3C-compliancy, cross-browser compatibility;  Adobe Photoshop/ImageReady, Adobe Illustrator, Swish, Paint Shop Pro</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">			
				<div class="subjects"><strong>New Media:</strong></div>
				<div class="skills">Macromedia Flash, Macromedia Authorware</div>
				<div class="clear"></div>
		</div>
		<div class="skillSet">		
				<div class="subjects"><strong>QA:</strong></div>
				<div class="skills">Experience designing test cases and test plans, Mercury Test Director, Mercury Quality Center</div>
				<div class="clear"></div>
		</div>
		<div class="h50"></div>