<dl class="table-display">

	<dt>Operating Systems:</dt>
	<dd>Windows XP/2000/NT/ME/98/95, MS DOS, Linux</dd>	
	
	<dt>Programming Languages:</dt>
	<dd>HTML/XHTML/DHTML; CSS1/CSS2; JavaScript/DOM-Scripting/jQuery;<br/>XML/XSL(XPath, XSLT);<br/>PHP 3/4/5, VB Script, JSP;<br/>Java, Visual Basic 6, VB.NET, C, C++, VBA;<br/>SQL, Oracle PL/SQL</dd>
	
	<dt>Technologies:</dt>
	<dd>XML, ASP.NET 2.0, JSP, ASP, OOD, RDBMS, ADO, Web 2.0, AJAX</dd>
	
	<dt>Databases:</dt>
	<dd>MySQL, Access 2000/2003, Microsoft SQL Server, Oracle 8i/9i</dd>	
	
	<dt>Software:</dt>
	<dd>MS Office 2003 (MS Word, MS Excel, MS Access, MS Power Point), Macromedia Dreamweaver, Macromedia HomeSite, phpMyAdmin, Zend Studio, WinSCP, Adobe Acrobat;  WinCVS, IntelliJ IDEA, CVS, SVN, Star Team</dd>
	
	<dt>Content Management:</dt>
	<dd>TOPS (TorStar appropriate Open Publishing System)</dd>
	
	<dt>e-Commerce:</dt>
	<dd>Zen Cart</dd>	
	
	<dt>Internet:</dt>
	<dd>Apache, Microsoft IIS, Tomcat, TCP/IP, HTTP, SMTP, FTP</dd>
	
	<dt>Web Design:</dt>
	<dd>Wireframes design, developing web site information architecture, layouts, templates, web site usability, accessibility, W3C-compliancy, cross-browser compatibility;  Adobe Photoshop/ImageReady, Adobe Illustrator, Swish, Paint Shop Pro</dd>	
	
	<dt>New Media:</dt>
	<dd>Macromedia Flash, Macromedia Authorware</dd>	
	
	<dt>QA:</dt>
	<dd>Experience designing test cases and test plans, Mercury Test Director, Mercury Quality Center</dd>	

</dl>