<div class="wrapper2 left">
	<strong>2005</strong> - <strong>CSS2</strong> Certificate (Brainbench.com)<br/>
	<strong>2005</strong> - <strong>XML</strong>  Certificate (Brainbench.com)<br/>
	<strong>2005</strong> - <strong>PHP4</strong> Certificate (Brainbench.com)<br/>
	<strong>2005</strong> - <strong>JavaScript</strong> Certificate (Brainbench.com)<br/>
	<strong>2002</strong> - <strong>SQL and PL/SQL</strong>  Certificate (Oracle)<br/>
	<strong>2000</strong> - <strong>MS SQL Server 6.5</strong> Certificate (Brainbench.com)
</div>		