
<div class="hor_nav">
     <div class="hor_menu_item_b"><a href="index.php"><strong>Home</strong></a></div>
     <div class="hor_menu_item_b"><a href="skills.php"><strong>Computer Skills</strong></a></div>
     <div class="hor_menu_item_b"><a href="portfolio.php">Portfolio</strong></a></div>
     <div class="hor_menu_item_b"><a href="education.php"><strong>Education</strong></a></div>
     <div class="hor_menu_item_b"><a href="contact.php"><strong>Contact&nbsp;Information</strong></a></div>
	 <div>&nbsp;</div>
</div>

<div>&nbsp;</div>
<div>&nbsp;</div>

