<ul class="l external">
	<li><a href="http://www.eyeweekly.com">www.eyeweekly.com</a> (built dynamic features for websites in .NET framework using TorStar Digital proprietary TOTEL technology and TOPS CMS, as well as XML, XSLT, xPath,  and Lucene search engine queries), 2007</li>
	<li><a href="http://www.toronto.com/movies">www.toronto.com/movies</a>  (built dynamic features for websites in .NET framework using TorStar Digital proprietary TOTEL technology and TOPS CMS, as well as XML, XSLT, xPath,  and Lucene search engine queries), 2007</li>
	<li><a href="http://mobile.thestar.com" class="external">mobile.thestar.com</a> (developed mobile CMS-based website mobile.thestar.com), 2007</li>
	<li><a href="http://www.mississauga.com">www.mississauga.com</a>  (built dynamic features for websites in .NET framework using TorStar Digital proprietary TOTEL technology and TOPS CMS, as well as XML, XSLT, xPath,  and Lucene search engine queries), 2007</li>
	<li><a href="http://www.virginmobile.ca" class="external">www.virginmobile.ca</a> (designed and developed XHTML/CSS/SSI template architecture for the whole website; developed clear, cross-browser compatible, valid, CSS-based code according to W3C standards for layouts, templates, web pages), 2005&nbsp;-&nbsp;2007</li>
	<li><a href="http://www.canada.com" class="external">www.canada.com</a>  (developed  cross-browser compatible, valid, W3C compliant XHTML code for layouts, templates, web pages for sections "Topics" and "Find it"), 2005</li>
	<li><a href="http://www.cci-eschool.com" class="external">www.cci-eschool.com </a>(Macromedia Authorware, Adobe Photoshop, created e-learning web modules for MS Office 2003), 2003 - 2004</li>
	<li><a href="http://www.desiconnection.ca" class="external">www.desiconnection.ca</a> (PHP-MySQL, back end, admin site, connected back end with front end), 2003</li>
	<li><a href="http://www.preetlari.com" class="external">www.preetlari.com</a> (PHP-MySQL, back end, admin site, connected back end with front end), 2003</li>
	<li><a href="http://www.bhajanawali.com" class="external">www.bhajanawali.com</a> (PHP-MySQL, back end, admin site, connected back end with front end), 2003</li>
	<li><a href="http://www.punjabilehran.com" class="external">www.punjabilehran.com</a> (PHP-MySQL, back end, admin site, connected back end with front end), 2003</li>
	<li><a href="http://www.laboterm.com" class="external">www.laboterm.com</a> (PHP-MySQL, full life cycle, both development and design), 2003</li>
</ul>
<div class="h50"></div>