<img src="images/win_xp.gif" alt="Microsoft Windows XP" width="225" height="42" /><div>&nbsp;</div>
<img src="images/linux1.gif" alt="Linux" width="112" height="48" /><div>&nbsp;</div>
<img src="images/php_logo.gif" alt="PHP" width="120" height="48" /><div>&nbsp;</div>
<img src="images/mysql-logo.gif" alt="MySQL" width="125" height="48" /><div>&nbsp;</div>
<!-- <p><img src="images/ASP.NET.gif" alt="ASP.NET" width="125" height="48" /></p>-->
<img src="images/java_logo.gif" alt="Java" width="28" height="48" /><div>&nbsp;</div>
<img src="images/oracle.gif" alt="Oracle" width="125" height="32" /><div>&nbsp;</div>
<img src="images/ms_office.gif" alt="Microsoft Office" width="84" height="31" />

